import toast from "react-hot-toast";

const generateMarkdown = (review) => {
  const fb = review.aiFeedback || {};
  const annotations = fb.annotations || [];

  let md = `# AI Code Review Report\n\n`;
  md += `**Language:** ${review.language}\n`;
  md += `**Date:** ${new Date(review.createdAt).toLocaleString()}\n`;
  md += `**Overall Score:** ${fb.score ?? "N/A"}%\n\n`;

  if (fb.subScores) {
    md += `## Quality Scores\n\n`;
    md += `| Dimension | Score |\n|---|---|\n`;
    Object.entries(fb.subScores).forEach(([key, val]) => {
      md += `| ${key.charAt(0).toUpperCase() + key.slice(1)} | ${val}/100 |\n`;
    });
    md += `\n`;
  }

  md += `## Summary\n\n${fb.summary || "N/A"}\n\n`;

  if (fb.complexity) {
    md += `## Complexity\n\n- **Time:** ${fb.complexity.time || "N/A"}\n- **Space:** ${fb.complexity.space || "N/A"}\n\n`;
  }

  if (annotations.length > 0) {
    md += `## Annotations (${annotations.length})\n\n`;
    md += `| Line | Severity | Category | Message |\n|---|---|---|---|\n`;
    annotations.forEach((a) => {
      md += `| ${a.line} | ${a.severity} | ${a.category} | ${a.message} |\n`;
    });
    md += `\n`;
  }

  const sections = [
    { title: "Bugs", data: fb.bugs },
    { title: "Suggestions", data: fb.suggestions },
    { title: "Best Practices", data: fb.bestPractices },
    { title: "Security", data: fb.security },
    { title: "Readability", data: fb.readability },
  ];

  sections.forEach(({ title, data }) => {
    if (data?.length > 0) {
      md += `## ${title}\n\n`;
      data.forEach((item) => {
        md += `- ${item}\n`;
      });
      md += `\n`;
    }
  });

  if (fb.improvedCode) {
    md += `## Improved Code\n\n\`\`\`${review.language}\n${fb.improvedCode}\n\`\`\`\n`;
  }

  md += `\n---\n*Generated by AI Code Reviewer*\n`;
  return md;
};

export const exportAsMarkdown = (review) => {
  const md = generateMarkdown(review);
  const blob = new Blob([md], { type: "text/markdown" });
  const link = document.createElement("a");
  link.href = URL.createObjectURL(blob);
  link.download = `review-${review.language}-${Date.now()}.md`;
  link.click();
  URL.revokeObjectURL(link.href);
  toast.success("Markdown report downloaded");
};

export const exportAsJSON = (review) => {
  const blob = new Blob([JSON.stringify(review, null, 2)], {
    type: "application/json",
  });
  const link = document.createElement("a");
  link.href = URL.createObjectURL(blob);
  link.download = `review-${review.language}-${Date.now()}.json`;
  link.click();
  URL.revokeObjectURL(link.href);
  toast.success("JSON report downloaded");
};

export const exportAsPDF = async (review) => {
  const md = generateMarkdown(review);

  // Convert markdown to styled HTML for PDF
  const html = `
    <div style="font-family: 'Segoe UI', Arial, sans-serif; padding: 40px; color: #1e293b; max-width: 800px;">
      <div style="text-align: center; margin-bottom: 30px; border-bottom: 2px solid #3b82f6; padding-bottom: 20px;">
        <h1 style="color: #3b82f6; margin: 0;">AI Code Review Report</h1>
        <p style="color: #64748b; margin-top: 8px;">Generated on ${new Date(review.createdAt).toLocaleString()}</p>
      </div>

      <div style="display: flex; justify-content: space-between; margin-bottom: 24px; gap: 16px;">
        <div style="background: #f1f5f9; padding: 16px; border-radius: 8px; flex: 1; text-align: center;">
          <div style="font-size: 28px; font-weight: 700; color: ${(review.aiFeedback?.score || 0) >= 70 ? '#10b981' : '#ef4444'};">${review.aiFeedback?.score || 0}%</div>
          <div style="font-size: 12px; color: #64748b;">Overall Score</div>
        </div>
        <div style="background: #f1f5f9; padding: 16px; border-radius: 8px; flex: 1; text-align: center;">
          <div style="font-size: 28px; font-weight: 700; color: #3b82f6;">${review.language}</div>
          <div style="font-size: 12px; color: #64748b;">Language</div>
        </div>
        <div style="background: #f1f5f9; padding: 16px; border-radius: 8px; flex: 1; text-align: center;">
          <div style="font-size: 28px; font-weight: 700; color: #8b5cf6;">${review.aiFeedback?.annotations?.length || 0}</div>
          <div style="font-size: 12px; color: #64748b;">Issues Found</div>
        </div>
      </div>

      <h2 style="color: #1e293b; border-bottom: 1px solid #e2e8f0; padding-bottom: 8px;">Summary</h2>
      <p style="color: #475569; line-height: 1.6;">${review.aiFeedback?.summary || 'N/A'}</p>

      ${review.aiFeedback?.annotations?.length > 0 ? `
        <h2 style="color: #1e293b; border-bottom: 1px solid #e2e8f0; padding-bottom: 8px; margin-top: 24px;">Annotations</h2>
        <table style="width: 100%; border-collapse: collapse; font-size: 13px;">
          <thead>
            <tr style="background: #f8fafc;">
              <th style="padding: 8px; border: 1px solid #e2e8f0; text-align: left;">Line</th>
              <th style="padding: 8px; border: 1px solid #e2e8f0; text-align: left;">Severity</th>
              <th style="padding: 8px; border: 1px solid #e2e8f0; text-align: left;">Category</th>
              <th style="padding: 8px; border: 1px solid #e2e8f0; text-align: left;">Message</th>
            </tr>
          </thead>
          <tbody>
            ${review.aiFeedback.annotations.map(a => `
              <tr>
                <td style="padding: 8px; border: 1px solid #e2e8f0;">${a.line}</td>
                <td style="padding: 8px; border: 1px solid #e2e8f0;"><span style="padding: 2px 6px; border-radius: 4px; font-size: 11px; background: ${a.severity === 'critical' ? '#fef2f2' : a.severity === 'warning' ? '#fffbeb' : '#eff6ff'}; color: ${a.severity === 'critical' ? '#ef4444' : a.severity === 'warning' ? '#f59e0b' : '#3b82f6'};">${a.severity}</span></td>
                <td style="padding: 8px; border: 1px solid #e2e8f0;">${a.category}</td>
                <td style="padding: 8px; border: 1px solid #e2e8f0;">${a.message}</td>
              </tr>
            `).join('')}
          </tbody>
        </table>
      ` : ''}

      ${['bugs', 'suggestions', 'bestPractices', 'security'].map(key => {
        const items = review.aiFeedback?.[key];
        if (!items?.length) return '';
        const title = key === 'bestPractices' ? 'Best Practices' : key.charAt(0).toUpperCase() + key.slice(1);
        return `
          <h2 style="color: #1e293b; border-bottom: 1px solid #e2e8f0; padding-bottom: 8px; margin-top: 24px;">${title}</h2>
          <ul style="color: #475569; line-height: 1.8; padding-left: 20px;">
            ${items.map(item => `<li>${item}</li>`).join('')}
          </ul>
        `;
      }).join('')}

      <div style="margin-top: 40px; padding-top: 16px; border-top: 1px solid #e2e8f0; text-align: center; color: #94a3b8; font-size: 12px;">
        Generated by AI Code Reviewer • ${new Date().toLocaleDateString()}
      </div>
    </div>
  `;

  try {
    const { default: html2pdf } = await import("html2pdf.js");
    const container = document.createElement("div");
    container.innerHTML = html;
    document.body.appendChild(container);

    await html2pdf()
      .set({
        margin: 10,
        filename: `review-${review.language}-${Date.now()}.pdf`,
        image: { type: "jpeg", quality: 0.98 },
        html2canvas: { scale: 2 },
        jsPDF: { unit: "mm", format: "a4", orientation: "portrait" },
      })
      .from(container)
      .save();

    document.body.removeChild(container);
    toast.success("PDF report downloaded");
  } catch (error) {
    console.error("PDF export failed:", error);
    toast.error("PDF export failed. Downloading as Markdown instead.");
    exportAsMarkdown(review);
  }
};
